// we're going import useEffect and useState
// so that we can fetch things.
import {useEffect, useState} from 'react'

import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import AgencyCard from '@components/AgencyCard';
import NavBar from '@components/NavBar';

// import my get agencies
import { getAgencies } from '@utils/api/agencies';

export default function Home() {
  // create our stateful values to fetch
  const [agencies, setAgencies] = useState() // undefined for now
  // I'm going to set the default of loading to true
  // because we're going to fetch on mount.
  const [isLoading, setIsLoading] = useState(true)

  // we're going create our loading of the agencies
  const loadAgencies = async () => {
    // fetch the data
    const data = await getAgencies()
    console.log(data)
    // set the agencies and loading to false.
    setAgencies(data)
    setIsLoading(false)
  }

  // use an effect on mount
  useEffect(()=> {
    loadAgencies()
  }, []) // on mount

  // let's handle the loading state
  if (isLoading) {
    return <>Loading...</>
  }
  // agencies will be populated

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Space Agencies
          </Typography>
          <Box
            sx={{
              marginTop: 2,
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
            }}
          >
            {/* We're going to loop through the data */
            agencies.results.map((agency)=> {
              return <AgencyCard
                // the ? image just checks if there is an image.
                imageUrl={agency.image?.image_url}
              />
            })
            }

          </Box>
        </Container>

    </div>
  )
}
