import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';

import NavBar from '@components/NavBar';

/*
Since the file path within pages is
/info/faq.js
The path on our local machine is going to be
http://localhost:3000/info/faq
This goes for any other type of static file mapping.
*/
export default function FAQ() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            Questions we hope you ask.
          </Typography>
          <Typography variant="p">
            No one really reads FAQs.
          </Typography>
        </Container>

    </div>
  )
}
