import { useState } from 'react'

import Head from 'next/head'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

export default function Home() {
  // create a stateful value for the quote data
  // we're adding a default value so there's no errors.
  const [quoteData, setQuoteData] = useState({
    "quote": "Please answer my questions",
    "author": "Dan"
  })
  // create a function that is async that will fetch the data
  const getRandomQuote = async () => {
    // it's on the same server you can use /api/random_quote with no domain.
    // note it's only capitalized like this because it's a constant
    // value that doesn't change.
    const RANDOM_QUOTE_URL = "/api/random_quote"
    // make the request like you would any other.
    const response = await fetch(RANDOM_QUOTE_URL)
    const data = await response.json()
    // set the state
    setQuoteData(data)
  }

  // update the quote on the page when you click the button.

  // one thing to note is that you need to handle
  // the loading state or the state before something
  // is fetched.

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={getRandomQuote}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
