// import the effect.
import { useState, useEffect } from 'react'
import Head from 'next/head'

import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';

import Navbar from '../components/Navbar';
import NewReviewForm from '../components/NewReviewForm';
import ReviewsList from '../components/ReviewsList';

import { getReviews } from '../utils/api/reviews';

export default function Home() {
  // I want you to create the stateful values we discussed
  // make the reviews stateful
  const [isLoading, setIsLoading] = useState(false)
  const [reviews, setReviews] = useState([])

  // I want you to make all of these inputs controlled.
  // I want you to create function that fetches the data
  // updates the 'reviews' stateful value

  // if you folks can make a function
  // call the backend api (it's on a different domain)
  // update the state of reviews.
  const loadReviews = async () => {
    // you can use try catch when you are trying to access
    // something outside of the application this would files/rest apis/network call.
    setIsLoading(true)
    try {
      // making the fetch request to the backend
      // it's on a different domain, so you need to specify the domain.
      const data = await getReviews()
      // to update the state of the page
      setReviews(data)
      setIsLoading(false)
    } catch (error) {
      // we're going to show later on a strategy of how to
      // display this error as a toast message.
      console.log(error)
      setIsLoading(false)
      // we're not handling the error state unless you folks really want to
      // please take a look at 16-hackernews example if you want to see an example of this.
    }
  }

  // I want you to import useeffect
  // create an effect that fires on mount
  // that will load the reviews
  // also handle the loading state.
  // create some circular progress to handle loading.
  useEffect(()=> {
    // call our function on mount.
    loadReviews()
  }, []) // launch this on mount.

  // if you're lazy and you don't want to look at the component profiler
  // you can always see the changes of a stateful using useEffect by listening
  // to the changes and printing it out to the console.
  useEffect(()=> {
    console.log(reviews)
  }, [reviews])



  return (
    <div>
      <Head>
        <title>Adaptation Reviews.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container maxWidth="md">
          <NewReviewForm
            loadReviews={loadReviews}
          />
          <Box
            sx={{
              pt: 2,
              pb: 2,
            }}
          >
            <Button
              variant="contained"
              onClick={loadReviews}
            >
              Load All Current Reviews
            </Button>
          </Box>
          <ReviewsList
            reviews={reviews}
            loadReviews={loadReviews}
          />

        </Container>
      </main>
    </div>
  )
}
