import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';

import NavBar from '@components/NavBar';

/*
This is a "dynamic" path where you can use
the variable "userId" inside of your application.


*/
export default function User() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            User
          </Typography>
          <Typography variant="p">
            This is a dynamic page.
          </Typography>
        </Container>

    </div>
  )
}
