import {useRouter} from 'next/router'

import Head from 'next/head'

import Typography from '@mui/material/Typography';
import Container from '@mui/material/Container';

import NavBar from '@components/NavBar';

/*
This is a "dynamic" path where you can use
the variable "userId" inside of your application.
The reason for this is because the file path (in pages)
is `user/[userId].js`
We can access this on the website with
http://localhost:3000/user/whateveryouwant

*/
export default function User() {
  // initialize the router
  const router = useRouter()
  // let's take a look at the contents
  console.log(router)

  // router.query holds all of the path
  // and query parameters for next.js on
  // the frontend we're going to destructure
  // and use the "userId" see above why
  // it's userId (or the filename in brackets)
  const { userId } = router.query
  // if you had a path to page that looked like this
  // http://localhost:3000/user/zoe?new_user=true&favourite_lang=javascript
  // you'll see that "new_user" and "favourite_lang" is also a part of the
  // the query object.


  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <Container sx={{paddingTop:2}} component="main" maxWidth="xs">

          <Typography variant="h3">
            {/* we can use the above directly in our code. */}
            Welcome user {userId}
          </Typography>
          <Typography variant="p">
            This is a dynamic page.
          </Typography>
          <ul>

          {/* see all query params */
          Object.keys(router.query).map((param, index)=> {
            return <li key={index}>{param}, value: {router.query[param]}</li>
          })}
          </ul>
        </Container>

    </div>
  )
}
